#include "protocol.h"
#include "event.h"

bool is_key(char c){
	return c == PROTOCOL_KEY_1 || c == PROTOCOL_KEY_2 || c == PROTOCOL_KEY_3 || c == PROTOCOL_KEY_4 || c == PROTOCOL_KEY_5 || c == PROTOCOL_KEY_6 || c == PROTOCOL_KEY_7 || c == PROTOCOL_KEY_8 || c == PROTOCOL_KEY_9 || c == PROTOCOL_KEY_0 || c == PROTOCOL_KEY_STAR || c == PROTOCOL_KEY_POUND || c == PROTOCOL_KEY_UP || c == PROTOCOL_KEY_DOWN || c == PROTOCOL_KEY_LEFT || c == PROTOCOL_KEY_RIGHT || c == PROTOCOL_KEY_OK || c == PROTOCOL_KEY_BACK || c == PROTOCOL_KEY_MUTE || c == PROTOCOL_KEY_VOL_UP || c == PROTOCOL_KEY_VOL_DOWN || c == PROTOCOL_KEY_HEADSET || c == PROTOCOL_KEY_REDIAL || c == PROTOCOL_KEY_BOOK || c == PROTOCOL_KEY_SPEAKER || c == PROTOCOL_KEY_TRANSFER || c == PROTOCOL_KEY_VOICEMAIL || c == PROTOCOL_KEY_FUNC_1 || c == PROTOCOL_KEY_FUNC_2 || c == PROTOCOL_KEY_FUNC_3 || c == PROTOCOL_KEY_FUNC_4 || c == PROTOCOL_KEY_LINE_1 || c == PROTOCOL_KEY_LINE_2 || c == PROTOCOL_KEY_LINE_3 || c == PROTOCOL_KEY_LINE_4 || c == PROTOCOL_KEY_LINE_5 || c == PROTOCOL_KEY_LINE_6 || c == PROTOCOL_KEY_LINE_7 || c == PROTOCOL_KEY_LINE_8 || c == PROTOCOL_KEY_HOOK;
}

char protocol_key_to_event_key(char c){
	switch(c){
		case PROTOCOL_KEY_1:
		        return KB_KEY_1;
		case PROTOCOL_KEY_2:
		        return KB_KEY_2;
		case PROTOCOL_KEY_3:
		        return KB_KEY_3;
		case PROTOCOL_KEY_4:
		        return KB_KEY_4;
		case PROTOCOL_KEY_5:
		        return KB_KEY_5;
		case PROTOCOL_KEY_6:
		        return KB_KEY_6;
		case PROTOCOL_KEY_7:
		        return KB_KEY_7;
		case PROTOCOL_KEY_8:
		        return KB_KEY_8;
		case PROTOCOL_KEY_9:
		        return KB_KEY_9;
		case PROTOCOL_KEY_0:
		        return KB_KEY_0;
		case PROTOCOL_KEY_STAR:
		        return KB_KEY_STAR;
		case PROTOCOL_KEY_POUND:
		        return KB_KEY_POUND;
		case PROTOCOL_KEY_UP:
		        return KB_KEY_UP;
		case PROTOCOL_KEY_DOWN:
		        return KB_KEY_DOWN;
		case PROTOCOL_KEY_LEFT:
		        return KB_KEY_LEFT;
		case PROTOCOL_KEY_RIGHT:
		        return KB_KEY_RIGHT;
		case PROTOCOL_KEY_OK:
		        return KB_KEY_OK;
		case PROTOCOL_KEY_BACK:
		        return KB_KEY_BACK;
		case PROTOCOL_KEY_MUTE:
		        return KB_KEY_MUTE;
		case PROTOCOL_KEY_VOL_UP:
		        return KB_KEY_VOL_UP;
		case PROTOCOL_KEY_VOL_DOWN:
		        return KB_KEY_VOL_DOWN;
		case PROTOCOL_KEY_HEADSET:
		        return KB_KEY_HEADSET;
		case PROTOCOL_KEY_REDIAL:
		        return KB_KEY_REDIAL;
		case PROTOCOL_KEY_BOOK:
		        return KB_KEY_BOOK;
		case PROTOCOL_KEY_SPEAKER:
		        return KB_KEY_SPEAKER;
		case PROTOCOL_KEY_TRANSFER:
		        return KB_KEY_TRANSFER;
		case PROTOCOL_KEY_VOICEMAIL:
		        return KB_KEY_VOICEMAIL;
		case PROTOCOL_KEY_FUNC_1:
		        return KB_KEY_FUNC_1;
		case PROTOCOL_KEY_FUNC_2:
		        return KB_KEY_FUNC_2;
		case PROTOCOL_KEY_FUNC_3:
		        return KB_KEY_FUNC_3;
		case PROTOCOL_KEY_FUNC_4:
		        return KB_KEY_FUNC_4;
		case PROTOCOL_KEY_LINE_1:
		        return KB_KEY_LINE_1;
		case PROTOCOL_KEY_LINE_2:
		        return KB_KEY_LINE_2;
		case PROTOCOL_KEY_LINE_3:
		        return KB_KEY_LINE_3;
		case PROTOCOL_KEY_LINE_4:
		        return KB_KEY_LINE_4;
		case PROTOCOL_KEY_LINE_5:
		        return KB_KEY_LINE_5;
		case PROTOCOL_KEY_LINE_6:
		        return KB_KEY_LINE_6;
		case PROTOCOL_KEY_LINE_7:
		        return KB_KEY_LINE_7;
		case PROTOCOL_KEY_LINE_8:
		        return KB_KEY_LINE_8;
		case PROTOCOL_KEY_HOOK:
		        return KB_KEY_HOOK;
		default:
			return 0;
	}
}

char event_key_to_protocol_key(char c){
	switch(c){
		case KB_KEY_1:
		        return PROTOCOL_KEY_1;
		case KB_KEY_2:
		        return PROTOCOL_KEY_2;
		case KB_KEY_3:
		        return PROTOCOL_KEY_3;
		case KB_KEY_4:
		        return PROTOCOL_KEY_4;
		case KB_KEY_5:
		        return PROTOCOL_KEY_5;
		case KB_KEY_6:
		        return PROTOCOL_KEY_6;
		case KB_KEY_7:
		        return PROTOCOL_KEY_7;
		case KB_KEY_8:
		        return PROTOCOL_KEY_8;
		case KB_KEY_9:
		        return PROTOCOL_KEY_9;
		case KB_KEY_0:
		        return PROTOCOL_KEY_0;
		case KB_KEY_STAR:
		        return PROTOCOL_KEY_STAR;
		case KB_KEY_POUND:
		        return PROTOCOL_KEY_POUND;
		case KB_KEY_UP:
		        return PROTOCOL_KEY_UP;
		case KB_KEY_DOWN:
		        return PROTOCOL_KEY_DOWN;
		case KB_KEY_LEFT:
		        return PROTOCOL_KEY_LEFT;
		case KB_KEY_RIGHT:
		        return PROTOCOL_KEY_RIGHT;
		case KB_KEY_OK:
		        return PROTOCOL_KEY_OK;
		case KB_KEY_BACK:
		        return PROTOCOL_KEY_BACK;
		case KB_KEY_MUTE:
		        return PROTOCOL_KEY_MUTE;
		case KB_KEY_VOL_UP:
		        return PROTOCOL_KEY_VOL_UP;
		case KB_KEY_VOL_DOWN:
		        return PROTOCOL_KEY_VOL_DOWN;
		case KB_KEY_HEADSET:
		        return PROTOCOL_KEY_HEADSET;
		case KB_KEY_REDIAL:
		        return PROTOCOL_KEY_REDIAL;
		case KB_KEY_BOOK:
		        return PROTOCOL_KEY_BOOK;
		case KB_KEY_SPEAKER:
		        return PROTOCOL_KEY_SPEAKER;
		case KB_KEY_TRANSFER:
		        return PROTOCOL_KEY_TRANSFER;
		case KB_KEY_VOICEMAIL:
		        return PROTOCOL_KEY_VOICEMAIL;
		case KB_KEY_FUNC_1:
		        return PROTOCOL_KEY_FUNC_1;
		case KB_KEY_FUNC_2:
		        return PROTOCOL_KEY_FUNC_2;
		case KB_KEY_FUNC_3:
		        return PROTOCOL_KEY_FUNC_3;
		case KB_KEY_FUNC_4:
		        return PROTOCOL_KEY_FUNC_4;
		case KB_KEY_LINE_1:
		        return PROTOCOL_KEY_LINE_1;
		case KB_KEY_LINE_2:
		        return PROTOCOL_KEY_LINE_2;
		case KB_KEY_LINE_3:
		        return PROTOCOL_KEY_LINE_3;
		case KB_KEY_LINE_4:
		        return PROTOCOL_KEY_LINE_4;
		case KB_KEY_LINE_5:
		        return PROTOCOL_KEY_LINE_5;
		case KB_KEY_LINE_6:
		        return PROTOCOL_KEY_LINE_6;
		case KB_KEY_LINE_7:
		        return PROTOCOL_KEY_LINE_7;
		case KB_KEY_LINE_8:
		        return PROTOCOL_KEY_LINE_8;
		case KB_KEY_HOOK:
		        return PROTOCOL_KEY_HOOK;
    	default:
			return 0;
	}
}